#!/bin/bash
pushd $OPENSHIFT_DATA_DIR
if [ ! -d ".rbenv" ]; then
  bash <(curl -L https://raw.githubusercontent.com/Seppone/openshift-rbenv-installer/master/bin/rbenv-installer)
  echo "gem: --no-rdoc --no-ri" > ${OPENSHIFT_DATA_DIR}.gemrc
fi
popd

export RBENV_ROOT=$OPENSHIFT_DATA_DIR/.rbenv
export PATH="$RBENV_ROOT/bin:$PATH"
export PATH="$HOME/.gem/bin/:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/bin:$PATH"

alias gem="gem --config-file ${OPENSHIFT_DATA_DIR}.gemrc"

. $OPENSHIFT_DATA_DIR/.rbenv/plugins/openshift-rbenv-installer/bin/rbenv-bootstrap-openshift

bundle="${HOME}/.gem/bin/bundle"

if [ ! -d "${OPENSHIFT_DATA_DIR}/.rbenv/versions/2.1.0" ]; then
  rbenv install 2.1.0
  rbenv global 2.1.0
fi

pushd $OPENSHIFT_REPO_DIR/
  rbenv local 2.1.0
popd

is_bundler_installed=$(gem query --name-matches '^bundler$'  --installed)
if [[ "$is_bundler_installed" != "true" ]]; then
  gem install bundler
  rbenv rehash
fi

if [ ! -d "${OPENSHIFT_DATA_DIR}/.rbenv/plugins/bundler" ]; then
  git clone -- git://github.com/carsomyr/rbenv-bundler.git \
  $OPENSHIFT_DATA_DIR/.rbenv/plugins/bundler
  rbenv rehash
fi

ruby -r bundler -e 'puts "Used Ruby Version is #{RUBY_VERSION}"'

pushd $OPENSHIFT_REPO_DIR/
  $bundle install --without development test --deployment --path $OPENSHIFT_DATA_DIR/vendor/bundle
  rbenv rehash
popd
