#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
export PATH=$OPENSHIFT_RUNTIME_DIR/bin:$PATH
export RBENV_ROOT=$OPENSHIFT_DATA_DIR/.rbenv
export PATH="$RBENV_ROOT/bin:$PATH"
export PATH="$HOME/.gem/bin/:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/bin:$PATH"

alias gem="gem --config-file ${OPENSHIFT_DATA_DIR}.gemrc"

. $OPENSHIFT_DATA_DIR/.rbenv/plugins/openshift-rbenv-installer/bin/rbenv-bootstrap-openshift

pushd $OPENSHIFT_REPO_DIR/
  bundle="${HOME}/.gem/bin/bundle"
  $bundle exec rails server -b $OPENSHIFT_DIY_IP -p $OPENSHIFT_DIY_PORT -e production -d
popd
